#!/bin/env bash

sudo curl -X PUT --data-binary @clean_config.json --unix-socket /var/run/unit/control.sock http://localhost/config/
# sudo curl -X PUT --data-binary @clean_certificates.json --unix-socket /var/run/unit/control.sock http://localhost/certificates/
